package com.hospital.appointment.entity;

import com.hospital.common.domain.BaseEntity;
import com.hospital.common.enums.AppointmentStatus;
import jakarta.persistence.*;
// Explicit accessors added to avoid relying on Lombok in environments where
// annotation processing may not be available for the language server/IDE.

import java.time.LocalDateTime;

@Entity
@Table(name = "appointments")
public class Appointment extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private Long patientId;

    @Column(nullable = false)
    private Long doctorId;

    @Column
    private Long departmentId;

    @Column(nullable = false)
    private LocalDateTime appointmentDateTime;

    @Enumerated(EnumType.STRING)
    @Column
    private AppointmentStatus status = AppointmentStatus.SCHEDULED;

    @Column
    private String notes;

    @Column
    private String reason;

    @Column
    private Integer durationMinutes;

    // createdAt/updatedAt are inherited from BaseEntity

    public Appointment() {
    }

    public Appointment(Long id, Long patientId, Long doctorId, Long departmentId, LocalDateTime appointmentDateTime, AppointmentStatus status, String notes, String reason, Integer durationMinutes) {
        this.id = id;
        this.patientId = patientId;
        this.doctorId = doctorId;
        this.departmentId = departmentId;
        this.appointmentDateTime = appointmentDateTime;
        this.status = status;
        this.notes = notes;
        this.reason = reason;
        this.durationMinutes = durationMinutes;
    }

    public Long getId() { return this.id; }
    public Long getPatientId() { return this.patientId; }
    public Long getDoctorId() { return this.doctorId; }
    public Long getDepartmentId() { return this.departmentId; }
    public LocalDateTime getAppointmentDateTime() { return this.appointmentDateTime; }
    public AppointmentStatus getStatus() { return this.status; }
    public String getNotes() { return this.notes; }
    public String getReason() { return this.reason; }
    public Integer getDurationMinutes() { return this.durationMinutes; }

    public void setStatus(AppointmentStatus status) { this.status = status; }
    public void setNotes(String notes) { this.notes = notes; }
    public void setAppointmentDateTime(LocalDateTime appointmentDateTime) { this.appointmentDateTime = appointmentDateTime; }
    public void setDurationMinutes(Integer durationMinutes) { this.durationMinutes = durationMinutes; }
    public void setReason(String reason) { this.reason = reason; }

    // Accessors for association ids (explicit, not generated by Lombok)
    public void setPatientId(Long patientId) { this.patientId = patientId; }
    public void setDoctorId(Long doctorId) { this.doctorId = doctorId; }
    public void setDepartmentId(Long departmentId) { this.departmentId = departmentId; }

    // Explicit getters for audit timestamps (avoid relying on Lombok in IDEs)
    @Override
    public java.time.LocalDateTime getCreatedAt() { return super.getCreatedAt(); }

    @Override
    public java.time.LocalDateTime getUpdatedAt() { return super.getUpdatedAt(); }

    // Manual builder fallback and toBuilder for compatibility with tests previously using Lombok
    public static AppointmentBuilder builder() { return new AppointmentBuilder(); }

    public AppointmentBuilder toBuilder() {
        return new AppointmentBuilder()
                .id(this.id)
                .patientId(this.patientId)
                .doctorId(this.doctorId)
                .departmentId(this.departmentId)
                .appointmentDateTime(this.appointmentDateTime)
                .status(this.status)
                .notes(this.notes)
                .reason(this.reason)
                .durationMinutes(this.durationMinutes);
    }

    public static class AppointmentBuilder {
        private Long id;
        private Long patientId;
        private Long doctorId;
        private Long departmentId;
        private java.time.LocalDateTime appointmentDateTime;
        private AppointmentStatus status;
        private String notes;
        private String reason;
        private Integer durationMinutes;

        public AppointmentBuilder id(Long id) { this.id = id; return this; }
        public AppointmentBuilder patientId(Long id) { this.patientId = id; return this; }
        public AppointmentBuilder doctorId(Long id) { this.doctorId = id; return this; }
        public AppointmentBuilder departmentId(Long id) { this.departmentId = id; return this; }
        public AppointmentBuilder appointmentDateTime(java.time.LocalDateTime dt) { this.appointmentDateTime = dt; return this; }
        public AppointmentBuilder status(AppointmentStatus s) { this.status = s; return this; }
        public AppointmentBuilder notes(String n) { this.notes = n; return this; }
        public AppointmentBuilder reason(String r) { this.reason = r; return this; }
        public AppointmentBuilder durationMinutes(Integer d) { this.durationMinutes = d; return this; }

        public Appointment build() {
            return new Appointment(this.id, this.patientId, this.doctorId, this.departmentId, this.appointmentDateTime, this.status == null ? AppointmentStatus.SCHEDULED : this.status, this.notes, this.reason, this.durationMinutes);
        }
    }
}
