package com.hospital.patient.domain;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDateTime;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.DecimalMax;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
* Vital Signs Entity
*
* Represents patient vital signs measurements.
* Used for monitoring patient health status.
*/
@Entity
@Table(name = "vital_signs", indexes = {
  @Index(name = "idx_vital_signs_patient", columnList = "patient_id"),
  @Index(name = "idx_vital_signs_timestamp", columnList = "measurement_timestamp"),
  @Index(name = "idx_vital_signs_device", columnList = "device_id")
})
@EntityListeners(AuditingEntityListener.class)
// Suppress 'unused' warnings: fields/constants are accessed via JPA/reflection or generated by Lombok;
// this keeps the Problems panel focused on real issues when annotation processing is unavailable.
@SuppressWarnings("unused")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class VitalSigns {
    private static final int MAX_VAL_100 = 100;
    private static final int VAL_200 = 200;
    private static final int VAL_300 = 300;
    private static final int VAL_500 = 500;
    private static final int VAL_50 = 50;
    private static final int VAL_20 = 20;
    private static final int VAL_5 = 5;
    private static final int VAL_4 = 4;
    private static final int VAL_255 = 255;
    private static final int VAL_11 = 11;
  /** Id. */

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;
  /** Patient. */

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "patient_id", nullable = false)
  @NotNull(message = "Patient is required")
  private Patient patient;
  /** Measurement timestamp. */

  @Column(name = "measurement_timestamp", nullable = false)
  @NotNull(message = "Measurement timestamp is required")
  private LocalDateTime measurementTimestamp;
  /** Device id. */

  @Column(name = "device_id", length = MAX_VAL_100)
  @Size(max = MAX_VAL_100, message = "Device ID cannot exceed 100 characters")
  private String deviceId;
  /** Location. */

  @Column(name = "location", length = MAX_VAL_100)
  @Size(max = MAX_VAL_100, message = "Location cannot exceed MAX_VAL_100 characters")
  private String location;

  // Vital Signs Measurements
  /** Heart rate. */
  @Column(name = "heart_rate")
  @Min(value = 0, message = "Heart rate must be positive")
  @Max(value = VAL_300, message = "Heart rate must be realistic")
  private Integer heartRate;
  /** Blood pressure systolic. */

  @Column(name = "blood_pressure_systolic")
  @Min(value = 0, message = "Systolic BP must be positive")
  @Max(value = VAL_300, message = "Systolic BP must be realistic")
  private Integer bloodPressureSystolic;
  /** Blood pressure diastolic. */

  @Column(name = "blood_pressure_diastolic")
  @Min(value = 0, message = "Diastolic BP must be positive")
  @Max(value = VAL_200, message = "Diastolic BP must be realistic")
  private Integer bloodPressureDiastolic;
  /** Temperature. */

  @Column(name = "temperature", precision = VAL_4, scale = 1)
  @DecimalMin(value = "30.0", message = "Temperature must be realistic")
  @DecimalMax(value = "50.0", message = "Temperature must be realistic")
  private BigDecimal temperature;
  /** Oxygen saturation. */

  @Column(name = "oxygen_saturation", precision = VAL_5, scale = 2)
  @DecimalMin(value = "0.0", message = "Oxygen saturation must be positive")
  @DecimalMax(value = "100.0", message = "Oxygen saturation cannot exceed 100%")
  private BigDecimal oxygenSaturation;
  /** Respiratory rate. */

  @Column(name = "respiratory_rate")
  @Min(value = 0, message = "Respiratory rate must be positive")
  @Max(value = MAX_VAL_100, message = "Respiratory rate must be realistic")
  private Integer respiratoryRate;
  /** Weight. */

  @Column(name = "weight", precision = VAL_5, scale = 2)
  @DecimalMin(value = "0.0", message = "Weight must be positive")
  @DecimalMax(value = "1000.0", message = "Weight must be realistic")
  private BigDecimal weight;
  /** Height. */

  @Column(name = "height", precision = VAL_5, scale = 2)
  @DecimalMin(value = "0.0", message = "Height must be positive")
  @DecimalMax(value = "300.0", message = "Height must be realistic")
  private BigDecimal height;

  @Enumerated(EnumType.STRING)
  @Column(name = "alert_level", nullable = false)
  @NotNull(message = "Alert level is required")
  @Builder.Default
  private AlertLevel alertLevel = AlertLevel.NORMAL;
  /** Notes. */

  @Column(name = "notes", columnDefinition = "TEXT")
  private String notes;

  // Manual builder fallback for IDEs/language servers that cannot run Lombok processors
  public static VitalSignsBuilder builderFallbackInternal() { return new VitalSignsBuilder(); }
  // Delegate matching Lombok API
  public static VitalSignsBuilder builder() { return builderFallbackInternal(); }

  public static class VitalSignsBuilder {
    private Long id;
    private LocalDateTime measurementTimestamp;
    private Integer heartRate;
    private Integer bloodPressureSystolic;
    private Integer bloodPressureDiastolic;
    private BigDecimal temperature;
    private BigDecimal oxygenSaturation;

    public VitalSignsBuilder id(Long id) { this.id = id; return this; }
    public VitalSignsBuilder measurementTimestamp(LocalDateTime ts) { this.measurementTimestamp = ts; return this; }
    public VitalSignsBuilder heartRate(Integer hr) { this.heartRate = hr; return this; }
    public VitalSignsBuilder bloodPressureSystolic(Integer s) { this.bloodPressureSystolic = s; return this; }
    public VitalSignsBuilder bloodPressureDiastolic(Integer d) { this.bloodPressureDiastolic = d; return this; }
    public VitalSignsBuilder temperature(BigDecimal t) { this.temperature = t; return this; }
    public VitalSignsBuilder oxygenSaturation(BigDecimal o) { this.oxygenSaturation = o; return this; }

    public VitalSigns build() {
      VitalSigns v = new VitalSigns();
      v.id = this.id;
      v.measurementTimestamp = this.measurementTimestamp;
      v.heartRate = this.heartRate;
      v.bloodPressureSystolic = this.bloodPressureSystolic;
      v.bloodPressureDiastolic = this.bloodPressureDiastolic;
      v.temperature = this.temperature;
      v.oxygenSaturation = this.oxygenSaturation;
      return v;
    }
  }

  // Audit Fields
  /** Created date. */
  @CreatedDate
  @Column(name = "created_date", nullable = false, updatable = false)
  private LocalDateTime createdDate;
  /** Recorded by. */

  @Column(name = "recorded_by", length = MAX_VAL_100)
  private String recordedBy;

  // Business Methods
  /**
   * Is critical.
   * @return Result.
   */
  public boolean isCritical() {
    return alertLevel == AlertLevel.CRITICAL;
  }
  /**
   * Is abnormal.
   * @return Result.
   */

  public boolean isAbnormal() {
    return alertLevel != AlertLevel.NORMAL;
  }
  /**
   * Get bmi.
   * @return Result.
   */

  public BigDecimal getBMI() {
    if (weight != null && height != null && height.compareTo(BigDecimal.ZERO) > 0) {
      BigDecimal heightInMeters = height.divide(BigDecimal.valueOf(MAX_VAL_100), 6, RoundingMode.HALF_UP);
      return weight.divide(heightInMeters.multiply(heightInMeters), 2, RoundingMode.HALF_UP);
    }
    return null;
  }

  public enum AlertLevel {
    NORMAL,
    WARNING,
    CRITICAL
  }
}
